### PR TITLE
Use wouter's Redirect instead of our custom redirect solution.

### LINKED ISSUE #941: Logging out of the application generates the wrong `nextPath` query in URL
image

It basically runs the `doRedirect` function in LoggedInFilter twice, so the `nextPath` gets nested. I'm not really sure why it does that, or what's the correct solution.

### PR DESCRIPTION
**Pull request by 2Pacalypse-**
Fixes #941

### CODE REVIEW

File: client/main-layout.tsx [hunk 1]
```diff
@@ -372,11 +372,9 @@ export function MainLayout() {
       <ConnectedLeftNav />
       <Content>
         <Switch>
-          <ConditionalRoute
-            path='/admin/:rest*'
-            filters={[IsAdminFilter]}
-            component={LoadableAdminPanel}
-          />
+          <Route path='/admin/:rest*'>
```
Comment (tec27) [inline client/main-layout.tsx:375]: You can just not render this Route in that case, rather than doing a redirect (not rendering the routes and being on an admin route will make it hit the fallback route here, which will redirect anyway)

**Review by tec27 — APPROVED** [review]
