### PR TITLE
Fix the spacing/padding issues in multiline TextFields.

### LINKED ISSUE #1068: Fix multi-line text-field and textarea spacing/padding
This is how it currently looks (I think it's even worse when there are trailing icons):

image

### PR DESCRIPTION
**Pull request by 2Pacalypse-**
Also fixes a bug which wouldn't render the correct size of textarea if the initial value was causing it to have multiple rows.

Fixes #1068

### CODE REVIEW

File: client/material/text-field.tsx [hunk 1]
```diff
@@ -212,6 +218,12 @@ export const TextField = React.forwardRef<HTMLInputElement, TextFieldProps>(
       [dense, rows],
     )
 
+    useEffect(() => {
```
Comment (tec27) [inline client/material/text-field.tsx:221]: You want this in a `useLayoutEffect` so the resize happens before the browser paints, otherwise you'll get a flash of the smaller size

**Review by tec27 — APPROVED** [review]
